AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the Community::CloudFormation::Delay resource type

Globals:
  Function:
    Timeout: 60  # docker start-up times can be long for SAM CLI

Resources:
  TestEntrypoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handlers.testEntrypoint
      Runtime: nodejs20.x
      CodeUri: ./

  TypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handlers.entrypoint
      Runtime: nodejs20.x
      CodeUri: ./

